"""
retail.py
---------
Implements the RetailTrader module: users who trade manually or via copy.

The Trade dataclass is defined here and shared with professional.py.

Typical usage:
    from traders.retail import RetailTraderEngine, Trade
    engine = RetailTraderEngine()
    trader = engine.create_retail_trader("Alice")
    trade  = engine.execute_trade(trader.id, "sim-a", "BUY", 5.0)
"""

import random
import uuid
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from state import state


# ── Random names for simulated traders ────────────────────────────────────
_SIMULATED_NAMES = [
    "Alice", "Bruno", "Carla", "Davide", "Elena",
    "Fabio", "Giulia", "Hamid", "Irene", "Luca",
    "Marco", "Nadia", "Omar", "Paola", "Quin",
    "Rosa", "Stefano", "Tina", "Ugo", "Vera",
]


# ── Trade dataclass (shared between retail and professionals) ─────────────

@dataclass
class Trade:
    """
    Represents a single buy or sell operation executed by a trader.

    Fields:
        id            — unique trade UUID
        trader_id     — id of the trader who executed the operation
        asset_id      — id of the traded asset
        action        — "BUY" or "SELL"
        quantity      — traded quantity
        price         — price at trade time
        timestamp     — simulation tick in which the trade occurred
        is_copy       — True if the trade was generated by the copy engine
        copied_from   — source professional_trader_id, if is_copy=True
        pnl_realized  — realized PnL (set only on SELL)
    """

    id: str
    trader_id: str
    asset_id: str
    action: str                   # "BUY" | "SELL"
    quantity: float
    price: float
    timestamp: int
    is_copy: bool = False
    copied_from: Optional[str] = None
    pnl_realized: float = 0.0

    def to_dict(self) -> dict:
        """Serializes the trade to a JSON-compatible dictionary."""
        return {
            "id": self.id,
            "trader_id": self.trader_id,
            "asset_id": self.asset_id,
            "action": self.action,
            "quantity": self.quantity,
            "price": self.price,
            "timestamp": self.timestamp,
            "is_copy": self.is_copy,
            "copied_from": self.copied_from,
            "pnl_realized": self.pnl_realized,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Trade":
        """Reconstructs a Trade from a snapshot dictionary."""
        return cls(
            id=data["id"],
            trader_id=data["trader_id"],
            asset_id=data["asset_id"],
            action=data["action"],
            quantity=data["quantity"],
            price=data["price"],
            timestamp=data["timestamp"],
            is_copy=data.get("is_copy", False),
            copied_from=data.get("copied_from"),
            pnl_realized=data.get("pnl_realized", 0.0),
        )


# ── RetailTrader dataclass ─────────────────────────────────────────────────

@dataclass
class RetailTrader:
    """
    Represents a retail trader: a user who trades manually or via copy.

    Fields:
        id              — unique UUID
        name            — display name
        is_real_user    — True only for the human user operating the dashboard
        balance         — available cash (decreases on BUY, increases on SELL)
        portfolio       — asset_id → quantity held
        avg_buy_prices  — asset_id → weighted average entry price
        trade_history   — list of Trades executed by this trader
        copied_traders  — list of professional_trader_ids being copied
        initial_balance — starting balance, used to compute total PnL
    """

    id: str
    name: str
    is_real_user: bool
    balance: float
    portfolio: Dict[str, float] = field(default_factory=dict)
    avg_buy_prices: Dict[str, float] = field(default_factory=dict)
    trade_history: List[Trade] = field(default_factory=list)
    copied_traders: List[str] = field(default_factory=list)
    initial_balance: float = 10000.0

    def to_dict(self) -> dict:
        """Serializes the retail trader to a JSON-compatible dictionary."""
        return {
            "id": self.id,
            "name": self.name,
            "is_real_user": self.is_real_user,
            "balance": self.balance,
            "portfolio": dict(self.portfolio),
            "avg_buy_prices": dict(self.avg_buy_prices),
            "trade_history": [t.to_dict() for t in self.trade_history],
            "copied_traders": list(self.copied_traders),
            "initial_balance": self.initial_balance,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "RetailTrader":
        """Reconstructs a RetailTrader from a snapshot dictionary."""
        trader = cls(
            id=data["id"],
            name=data["name"],
            is_real_user=data["is_real_user"],
            balance=data["balance"],
            portfolio=data.get("portfolio", {}),
            avg_buy_prices=data.get("avg_buy_prices", {}),
            copied_traders=data.get("copied_traders", []),
            initial_balance=data.get("initial_balance", 10000.0),
        )
        trader.trade_history = [Trade.from_dict(t) for t in data.get("trade_history", [])]
        return trader


# ── Engine ─────────────────────────────────────────────────────────────────

class RetailTraderEngine:
    """
    Manages retail trader operations: creation, trade execution and calculations.

    Does not modify state.platform_pnl — that responsibility belongs to the copy engine.
    """

    def create_retail_trader(
        self,
        name: str,
        initial_balance: float = 10000.0,
        is_real_user: bool = False,
    ) -> RetailTrader:
        """
        Creates a new RetailTrader, adds it to state.retail_traders and returns it.

        Args:
            name:            trader name.
            initial_balance: starting balance in simulated currency.
            is_real_user:    True if this corresponds to the human user of the dashboard.

        Returns:
            The newly created RetailTrader.
        """
        trader = RetailTrader(
            id=str(uuid.uuid4()),
            name=name,
            is_real_user=is_real_user,
            balance=initial_balance,
            initial_balance=initial_balance,
        )
        state.retail_traders[trader.id] = trader
        return trader

    def execute_trade(
        self,
        trader_id: str,
        asset_id: str,
        action: str,
        quantity: float,
        is_copy: bool = False,
        copied_from: Optional[str] = None,
    ) -> Trade:
        """
        Executes a buy or sell operation for a retail trader.

        BUY:
            - Checks that trader.balance >= quantity * current_price
            - Updates portfolio and avg_buy_prices (weighted average)
            - Deducts the total cost from balance
            - Records the Trade in trade_history and state.trade_log

        SELL:
            - Checks that portfolio[asset_id] >= quantity
            - Computes pnl_realized = (current_price - avg_buy_price) * quantity
            - Updates balance and portfolio
            - Removes the key from portfolio/avg_buy_prices on a full sale
            - Records the Trade in trade_history and state.trade_log

        Args:
            trader_id:   RetailTrader id.
            asset_id:    id of the asset to trade.
            action:      "BUY" or "SELL".
            quantity:    asset quantity.
            is_copy:     True if generated by the copy engine.
            copied_from: source professional_trader_id (if is_copy=True).

        Returns:
            The newly executed Trade.

        Raises:
            KeyError:   if trader_id or asset_id do not exist.
            ValueError: if the balance is insufficient (BUY) or the portfolio is
                        insufficient (SELL), with a descriptive message.
        """
        trader = state.retail_traders[trader_id]
        current_price = state.assets[asset_id].current_price
        pnl_realized = 0.0

        if action == "BUY":
            cost = quantity * current_price
            if trader.balance < cost:
                raise ValueError(
                    f"Balance insufficiente per {trader.name}: "
                    f"richiesto {cost:.2f}, disponibile {trader.balance:.2f}."
                )
            # Update the weighted average entry price
            old_qty = trader.portfolio.get(asset_id, 0.0)
            old_avg = trader.avg_buy_prices.get(asset_id, 0.0)
            new_qty = old_qty + quantity
            trader.avg_buy_prices[asset_id] = (
                (old_avg * old_qty + current_price * quantity) / new_qty
            )
            trader.portfolio[asset_id] = new_qty
            trader.balance -= cost

        elif action == "SELL":
            held = trader.portfolio.get(asset_id, 0.0)
            if held < quantity:
                raise ValueError(
                    f"Portafoglio insufficiente per {trader.name}: "
                    f"richiesto {quantity:.4f} di {asset_id}, posseduto {held:.4f}."
                )
            avg_buy = trader.avg_buy_prices.get(asset_id, 0.0)
            pnl_realized = (current_price - avg_buy) * quantity
            trader.balance += quantity * current_price
            remaining = held - quantity
            if remaining < 1e-9:
                # Full sale: remove keys for cleanliness
                trader.portfolio.pop(asset_id, None)
                trader.avg_buy_prices.pop(asset_id, None)
            else:
                trader.portfolio[asset_id] = remaining
                # avg_buy_price stays unchanged on a partial sale

        else:
            raise ValueError(f"Azione non valida: '{action}'. Usa 'BUY' o 'SELL'.")

        trade = Trade(
            id=str(uuid.uuid4()),
            trader_id=trader_id,
            asset_id=asset_id,
            action=action,
            quantity=quantity,
            price=current_price,
            timestamp=state.current_tick,
            is_copy=is_copy,
            copied_from=copied_from,
            pnl_realized=pnl_realized,
        )
        trader.trade_history.append(trade)
        state.trade_log.append(trade)
        return trade

    def get_portfolio_value(self, trader_id: str) -> float:
        """
        Computes the total portfolio value of the trader.

        Value = balance + Σ(portfolio[asset_id] * current_price[asset_id])

        Args:
            trader_id: RetailTrader id.

        Returns:
            float: total value in simulated currency.
        """
        trader = state.retail_traders[trader_id]
        holdings_value = sum(
            qty * state.assets[asset_id].current_price
            for asset_id, qty in trader.portfolio.items()
            if asset_id in state.assets
        )
        return trader.balance + holdings_value

    def get_total_pnl(self, trader_id: str) -> float:
        """
        Computes the trader's total PnL relative to the initial balance.

        Total PnL = current_portfolio_value - initial_balance

        Args:
            trader_id: RetailTrader id.

        Returns:
            float: total PnL (positive = gain, negative = loss).
        """
        return self.get_portfolio_value(trader_id) - state.retail_traders[trader_id].initial_balance

    def get_summary(self, trader_id: str) -> dict:
        """
        Returns a summary dictionary for the retail trader.

        Returned fields:
            id, name, balance, portfolio_value, total_pnl,
            n_trades, copied_traders

        Args:
            trader_id: RetailTrader id.

        Returns:
            dict with trader data.
        """
        trader = state.retail_traders[trader_id]
        portfolio_value = self.get_portfolio_value(trader_id)
        return {
            "id": trader.id,
            "name": trader.name,
            "balance": round(trader.balance, 4),
            "portfolio_value": round(portfolio_value, 4),
            "total_pnl": round(portfolio_value - trader.initial_balance, 4),
            "n_trades": len(trader.trade_history),
            "copied_traders": list(trader.copied_traders),
        }

    def create_simulated_retailers(self, n: int = 10) -> List[RetailTrader]:
        """
        Creates N simulated retail traders with random names and balances.

        Each trader has a random starting balance between 5000 and 20000.
        Useful for populating the simulation without a real user.

        Args:
            n: number of simulated traders to create.

        Returns:
            List of created RetailTraders.
        """
        traders = []
        name_pool = list(_SIMULATED_NAMES)
        random.shuffle(name_pool)

        for i in range(n):
            # Recycle names if n > len(_SIMULATED_NAMES)
            name = name_pool[i % len(name_pool)]
            if i >= len(name_pool):
                name = f"{name}_{i}"
            balance = round(random.uniform(5000.0, 20000.0), 2)
            trader = self.create_retail_trader(
                name=name,
                initial_balance=balance,
                is_real_user=False,
            )
            traders.append(trader)

        return traders


# ── Global instance ────────────────────────────────────────────────────────
# Importable directly: from traders.retail import retail_engine
retail_engine = RetailTraderEngine()
